// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/bflad/petstore-sdk/models/components"
)

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	User *components.User
}

func (o *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateUserResponse) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}
