// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/bflad/petstore-sdk/models/components"
)

type LogoutUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *LogoutUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
